-- ============================================================================
-- eventos  --  o events_* do GA4 totalmente vetorizado: uma linha por evento,
--             uma coluna por valor. Nenhum STRUCT, nenhum array dentro de celula.
--
--   Origem:  raulpavao-com-br.analytics_552236564.events_*   (export nativo GA4)
--   Destino: raulpavao-com-br.dados_tratados.eventos
--   Grao:    uma linha por evento. Janela: ultimos 28 dias, sem intraday.
--
-- Todo campo do schema do export vira coluna <caminho>_<campo> (fica NULL onde a
-- propriedade nao usa). Cada chave de event_params vira param_<chave> com o valor.
-- Cada event_name vira um indicador evento_<nome> (1 na linha, some no GROUP BY).
-- O array items muda o grao -> view irma dados_tratados.eventos_itens.
--
-- Pra outra propriedade: revise a lista evento_<nome> (SELECT DISTINCT event_name)
-- e param_<chave> (SELECT DISTINCT key FROM ..., UNNEST(event_params)).
-- ============================================================================
CREATE OR REPLACE VIEW `raulpavao-com-br.dados_tratados.eventos` AS
SELECT
  CONCAT('analytics_552236564.events_', _TABLE_SUFFIX) AS registro_origem,
  event_date,
  event_timestamp,
  event_previous_timestamp,
  event_name,
  event_value_in_usd,
  event_bundle_sequence_id,
  event_server_timestamp_offset,
  event_original_occurrence_timestamp,
  event_dimensions.hostname AS event_dimensions_hostname,
  user_id,
  user_pseudo_id,
  user_first_touch_timestamp,
  is_active_user,
  stream_id,
  platform,
  batch_event_index,
  batch_ordering_id,
  batch_page_id,
  -- event_name vetorizado: 1 indicador por nome de evento
  IF(event_name = 'click', 1, 0) AS evento_click,
  IF(event_name = 'first_visit', 1, 0) AS evento_first_visit,
  IF(event_name = 'page_view', 1, 0) AS evento_page_view,
  IF(event_name = 'scroll', 1, 0) AS evento_scroll,
  IF(event_name = 'session_start', 1, 0) AS evento_session_start,
  IF(event_name = 'user_engagement', 1, 0) AS evento_user_engagement,
  -- user_ltv
  user_ltv.revenue AS user_ltv_revenue,
  user_ltv.currency AS user_ltv_currency,
  -- privacy_info
  privacy_info.analytics_storage AS privacy_info_analytics_storage,
  privacy_info.ads_storage AS privacy_info_ads_storage,
  privacy_info.uses_transient_token AS privacy_info_uses_transient_token,
  -- device
  device.category AS device_category,
  device.mobile_brand_name AS device_mobile_brand_name,
  device.mobile_model_name AS device_mobile_model_name,
  device.mobile_marketing_name AS device_mobile_marketing_name,
  device.mobile_os_hardware_model AS device_mobile_os_hardware_model,
  device.operating_system AS device_operating_system,
  device.operating_system_version AS device_operating_system_version,
  device.vendor_id AS device_vendor_id,
  device.advertising_id AS device_advertising_id,
  device.language AS device_language,
  device.is_limited_ad_tracking AS device_is_limited_ad_tracking,
  device.time_zone_offset_seconds AS device_time_zone_offset_seconds,
  device.browser AS device_browser,
  device.browser_version AS device_browser_version,
  device.web_info.browser AS device_web_info_browser,
  device.web_info.browser_version AS device_web_info_browser_version,
  device.web_info.hostname AS device_web_info_hostname,
  -- geo
  geo.continent AS geo_continent,
  geo.sub_continent AS geo_sub_continent,
  geo.country AS geo_country,
  geo.region AS geo_region,
  geo.city AS geo_city,
  geo.metro AS geo_metro,
  -- app_info
  app_info.id AS app_info_id,
  app_info.version AS app_info_version,
  app_info.install_store AS app_info_install_store,
  app_info.firebase_app_id AS app_info_firebase_app_id,
  app_info.install_source AS app_info_install_source,
  -- collected_traffic_source
  collected_traffic_source.manual_campaign_id AS collected_traffic_source_manual_campaign_id,
  collected_traffic_source.manual_campaign_name AS collected_traffic_source_manual_campaign_name,
  collected_traffic_source.manual_source AS collected_traffic_source_manual_source,
  collected_traffic_source.manual_medium AS collected_traffic_source_manual_medium,
  collected_traffic_source.manual_term AS collected_traffic_source_manual_term,
  collected_traffic_source.manual_content AS collected_traffic_source_manual_content,
  collected_traffic_source.manual_source_platform AS collected_traffic_source_manual_source_platform,
  collected_traffic_source.manual_creative_format AS collected_traffic_source_manual_creative_format,
  collected_traffic_source.manual_marketing_tactic AS collected_traffic_source_manual_marketing_tactic,
  collected_traffic_source.gclid AS collected_traffic_source_gclid,
  collected_traffic_source.dclid AS collected_traffic_source_dclid,
  collected_traffic_source.srsltid AS collected_traffic_source_srsltid,
  -- traffic_source (primeiro toque)
  traffic_source.name AS traffic_source_name,
  traffic_source.medium AS traffic_source_medium,
  traffic_source.source AS traffic_source_source,
  -- session_traffic_source_last_click (todas as 6 sub-structs)
  session_traffic_source_last_click.manual_campaign.campaign_id AS session_traffic_source_last_click_manual_campaign_campaign_id,
  session_traffic_source_last_click.manual_campaign.campaign_name AS session_traffic_source_last_click_manual_campaign_campaign_name,
  session_traffic_source_last_click.manual_campaign.source AS session_traffic_source_last_click_manual_campaign_source,
  session_traffic_source_last_click.manual_campaign.medium AS session_traffic_source_last_click_manual_campaign_medium,
  session_traffic_source_last_click.manual_campaign.term AS session_traffic_source_last_click_manual_campaign_term,
  session_traffic_source_last_click.manual_campaign.content AS session_traffic_source_last_click_manual_campaign_content,
  session_traffic_source_last_click.manual_campaign.source_platform AS session_traffic_source_last_click_manual_campaign_source_platform,
  session_traffic_source_last_click.manual_campaign.creative_format AS session_traffic_source_last_click_manual_campaign_creative_format,
  session_traffic_source_last_click.manual_campaign.marketing_tactic AS session_traffic_source_last_click_manual_campaign_marketing_tactic,
  session_traffic_source_last_click.google_ads_campaign.customer_id AS session_traffic_source_last_click_google_ads_campaign_customer_id,
  session_traffic_source_last_click.google_ads_campaign.account_name AS session_traffic_source_last_click_google_ads_campaign_account_name,
  session_traffic_source_last_click.google_ads_campaign.campaign_id AS session_traffic_source_last_click_google_ads_campaign_campaign_id,
  session_traffic_source_last_click.google_ads_campaign.campaign_name AS session_traffic_source_last_click_google_ads_campaign_campaign_name,
  session_traffic_source_last_click.google_ads_campaign.ad_group_id AS session_traffic_source_last_click_google_ads_campaign_ad_group_id,
  session_traffic_source_last_click.google_ads_campaign.ad_group_name AS session_traffic_source_last_click_google_ads_campaign_ad_group_name,
  session_traffic_source_last_click.cross_channel_campaign.campaign_id AS session_traffic_source_last_click_cross_channel_campaign_campaign_id,
  session_traffic_source_last_click.cross_channel_campaign.campaign_name AS session_traffic_source_last_click_cross_channel_campaign_campaign_name,
  session_traffic_source_last_click.cross_channel_campaign.source AS session_traffic_source_last_click_cross_channel_campaign_source,
  session_traffic_source_last_click.cross_channel_campaign.medium AS session_traffic_source_last_click_cross_channel_campaign_medium,
  session_traffic_source_last_click.cross_channel_campaign.source_platform AS session_traffic_source_last_click_cross_channel_campaign_source_platform,
  session_traffic_source_last_click.cross_channel_campaign.default_channel_group AS session_traffic_source_last_click_cross_channel_campaign_default_channel_group,
  session_traffic_source_last_click.cross_channel_campaign.primary_channel_group AS session_traffic_source_last_click_cross_channel_campaign_primary_channel_group,
  session_traffic_source_last_click.sa360_campaign.campaign_id AS session_traffic_source_last_click_sa360_campaign_campaign_id,
  session_traffic_source_last_click.sa360_campaign.campaign_name AS session_traffic_source_last_click_sa360_campaign_campaign_name,
  session_traffic_source_last_click.sa360_campaign.source AS session_traffic_source_last_click_sa360_campaign_source,
  session_traffic_source_last_click.sa360_campaign.medium AS session_traffic_source_last_click_sa360_campaign_medium,
  session_traffic_source_last_click.sa360_campaign.ad_group_id AS session_traffic_source_last_click_sa360_campaign_ad_group_id,
  session_traffic_source_last_click.sa360_campaign.ad_group_name AS session_traffic_source_last_click_sa360_campaign_ad_group_name,
  session_traffic_source_last_click.sa360_campaign.creative_format AS session_traffic_source_last_click_sa360_campaign_creative_format,
  session_traffic_source_last_click.sa360_campaign.engine_account_name AS session_traffic_source_last_click_sa360_campaign_engine_account_name,
  session_traffic_source_last_click.sa360_campaign.engine_account_type AS session_traffic_source_last_click_sa360_campaign_engine_account_type,
  session_traffic_source_last_click.sa360_campaign.manager_account_name AS session_traffic_source_last_click_sa360_campaign_manager_account_name,
  session_traffic_source_last_click.cm360_campaign.campaign_id AS session_traffic_source_last_click_cm360_campaign_campaign_id,
  session_traffic_source_last_click.cm360_campaign.campaign_name AS session_traffic_source_last_click_cm360_campaign_campaign_name,
  session_traffic_source_last_click.cm360_campaign.source AS session_traffic_source_last_click_cm360_campaign_source,
  session_traffic_source_last_click.cm360_campaign.medium AS session_traffic_source_last_click_cm360_campaign_medium,
  session_traffic_source_last_click.cm360_campaign.account_id AS session_traffic_source_last_click_cm360_campaign_account_id,
  session_traffic_source_last_click.cm360_campaign.account_name AS session_traffic_source_last_click_cm360_campaign_account_name,
  session_traffic_source_last_click.cm360_campaign.advertiser_id AS session_traffic_source_last_click_cm360_campaign_advertiser_id,
  session_traffic_source_last_click.cm360_campaign.advertiser_name AS session_traffic_source_last_click_cm360_campaign_advertiser_name,
  session_traffic_source_last_click.cm360_campaign.creative_id AS session_traffic_source_last_click_cm360_campaign_creative_id,
  session_traffic_source_last_click.cm360_campaign.creative_format AS session_traffic_source_last_click_cm360_campaign_creative_format,
  session_traffic_source_last_click.cm360_campaign.creative_name AS session_traffic_source_last_click_cm360_campaign_creative_name,
  session_traffic_source_last_click.cm360_campaign.creative_type AS session_traffic_source_last_click_cm360_campaign_creative_type,
  session_traffic_source_last_click.cm360_campaign.creative_type_id AS session_traffic_source_last_click_cm360_campaign_creative_type_id,
  session_traffic_source_last_click.cm360_campaign.creative_version AS session_traffic_source_last_click_cm360_campaign_creative_version,
  session_traffic_source_last_click.cm360_campaign.placement_id AS session_traffic_source_last_click_cm360_campaign_placement_id,
  session_traffic_source_last_click.cm360_campaign.placement_cost_structure AS session_traffic_source_last_click_cm360_campaign_placement_cost_structure,
  session_traffic_source_last_click.cm360_campaign.placement_name AS session_traffic_source_last_click_cm360_campaign_placement_name,
  session_traffic_source_last_click.cm360_campaign.rendering_id AS session_traffic_source_last_click_cm360_campaign_rendering_id,
  session_traffic_source_last_click.cm360_campaign.site_id AS session_traffic_source_last_click_cm360_campaign_site_id,
  session_traffic_source_last_click.cm360_campaign.site_name AS session_traffic_source_last_click_cm360_campaign_site_name,
  session_traffic_source_last_click.dv360_campaign.campaign_id AS session_traffic_source_last_click_dv360_campaign_campaign_id,
  session_traffic_source_last_click.dv360_campaign.campaign_name AS session_traffic_source_last_click_dv360_campaign_campaign_name,
  session_traffic_source_last_click.dv360_campaign.source AS session_traffic_source_last_click_dv360_campaign_source,
  session_traffic_source_last_click.dv360_campaign.medium AS session_traffic_source_last_click_dv360_campaign_medium,
  session_traffic_source_last_click.dv360_campaign.advertiser_id AS session_traffic_source_last_click_dv360_campaign_advertiser_id,
  session_traffic_source_last_click.dv360_campaign.advertiser_name AS session_traffic_source_last_click_dv360_campaign_advertiser_name,
  session_traffic_source_last_click.dv360_campaign.creative_id AS session_traffic_source_last_click_dv360_campaign_creative_id,
  session_traffic_source_last_click.dv360_campaign.creative_format AS session_traffic_source_last_click_dv360_campaign_creative_format,
  session_traffic_source_last_click.dv360_campaign.creative_name AS session_traffic_source_last_click_dv360_campaign_creative_name,
  session_traffic_source_last_click.dv360_campaign.exchange_id AS session_traffic_source_last_click_dv360_campaign_exchange_id,
  session_traffic_source_last_click.dv360_campaign.exchange_name AS session_traffic_source_last_click_dv360_campaign_exchange_name,
  session_traffic_source_last_click.dv360_campaign.insertion_order_id AS session_traffic_source_last_click_dv360_campaign_insertion_order_id,
  session_traffic_source_last_click.dv360_campaign.insertion_order_name AS session_traffic_source_last_click_dv360_campaign_insertion_order_name,
  session_traffic_source_last_click.dv360_campaign.line_item_id AS session_traffic_source_last_click_dv360_campaign_line_item_id,
  session_traffic_source_last_click.dv360_campaign.line_item_name AS session_traffic_source_last_click_dv360_campaign_line_item_name,
  session_traffic_source_last_click.dv360_campaign.partner_id AS session_traffic_source_last_click_dv360_campaign_partner_id,
  session_traffic_source_last_click.dv360_campaign.partner_name AS session_traffic_source_last_click_dv360_campaign_partner_name,
  -- ecommerce (nivel evento)
  ecommerce.total_item_quantity AS ecommerce_total_item_quantity,
  ecommerce.purchase_revenue_in_usd AS ecommerce_purchase_revenue_in_usd,
  ecommerce.purchase_revenue AS ecommerce_purchase_revenue,
  ecommerce.refund_value_in_usd AS ecommerce_refund_value_in_usd,
  ecommerce.refund_value AS ecommerce_refund_value,
  ecommerce.shipping_value_in_usd AS ecommerce_shipping_value_in_usd,
  ecommerce.shipping_value AS ecommerce_shipping_value,
  ecommerce.tax_value_in_usd AS ecommerce_tax_value_in_usd,
  ecommerce.tax_value AS ecommerce_tax_value,
  ecommerce.unique_items AS ecommerce_unique_items,
  ecommerce.transaction_id AS ecommerce_transaction_id,
  -- publisher
  publisher.ad_revenue_in_usd AS publisher_ad_revenue_in_usd,
  publisher.ad_format AS publisher_ad_format,
  publisher.ad_source_name AS publisher_ad_source_name,
  publisher.ad_unit_id AS publisher_ad_unit_id,
  -- event_params: uma coluna por chave, sem array em celula
  (SELECT p.value.string_value FROM UNNEST(event_params) p WHERE p.key = 'anonymize_ip') AS param_anonymize_ip,
  (SELECT p.value.int_value FROM UNNEST(event_params) p WHERE p.key = 'batch_ordering_id') AS param_batch_ordering_id,
  (SELECT p.value.int_value FROM UNNEST(event_params) p WHERE p.key = 'batch_page_id') AS param_batch_page_id,
  (SELECT p.value.string_value FROM UNNEST(event_params) p WHERE p.key = 'campaign') AS param_campaign,
  (SELECT p.value.int_value FROM UNNEST(event_params) p WHERE p.key = 'engaged_session_event') AS param_engaged_session_event,
  (SELECT p.value.int_value FROM UNNEST(event_params) p WHERE p.key = 'engagement_time_msec') AS param_engagement_time_msec,
  (SELECT p.value.int_value FROM UNNEST(event_params) p WHERE p.key = 'entrances') AS param_entrances,
  (SELECT p.value.int_value FROM UNNEST(event_params) p WHERE p.key = 'ga_session_id') AS param_ga_session_id,
  (SELECT p.value.int_value FROM UNNEST(event_params) p WHERE p.key = 'ga_session_number') AS param_ga_session_number,
  (SELECT p.value.string_value FROM UNNEST(event_params) p WHERE p.key = 'ignore_referrer') AS param_ignore_referrer,
  (SELECT p.value.string_value FROM UNNEST(event_params) p WHERE p.key = 'link_classes') AS param_link_classes,
  (SELECT p.value.string_value FROM UNNEST(event_params) p WHERE p.key = 'link_domain') AS param_link_domain,
  (SELECT p.value.string_value FROM UNNEST(event_params) p WHERE p.key = 'link_url') AS param_link_url,
  (SELECT p.value.string_value FROM UNNEST(event_params) p WHERE p.key = 'medium') AS param_medium,
  (SELECT p.value.string_value FROM UNNEST(event_params) p WHERE p.key = 'outbound') AS param_outbound,
  (SELECT p.value.string_value FROM UNNEST(event_params) p WHERE p.key = 'page_location') AS param_page_location,
  (SELECT p.value.string_value FROM UNNEST(event_params) p WHERE p.key = 'page_path') AS param_page_path,
  (SELECT p.value.string_value FROM UNNEST(event_params) p WHERE p.key = 'page_referrer') AS param_page_referrer,
  (SELECT p.value.string_value FROM UNNEST(event_params) p WHERE p.key = 'page_title') AS param_page_title,
  (SELECT p.value.int_value FROM UNNEST(event_params) p WHERE p.key = 'percent_scrolled') AS param_percent_scrolled,
  (SELECT COALESCE(p.value.string_value, CAST(p.value.int_value AS STRING)) FROM UNNEST(event_params) p WHERE p.key = 'session_engaged') AS param_session_engaged,
  (SELECT p.value.string_value FROM UNNEST(event_params) p WHERE p.key = 'source') AS param_source
FROM `raulpavao-com-br.analytics_552236564.events_*`
WHERE _TABLE_SUFFIX NOT LIKE 'intraday%'
  AND _TABLE_SUFFIX >= FORMAT_DATE('%Y%m%d', DATE_SUB(CURRENT_DATE(), INTERVAL 28 DAY));
